# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170928_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='owner',
            field=models.CharField(default='brahim', max_length=100),
        ),
    ]
